<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net$(RuntimeMajor).0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="YukkuriMovieMaker"><HintPath>$(Ymm4Directory)\YukkuriMovieMaker.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="YukkuriMovieMaker.Plugin"><HintPath>$(Ymm4Directory)\YukkuriMovieMaker.Plugin.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="YukkuriMovieMaker.Settings"><HintPath>$(Ymm4Directory)\YukkuriMovieMaker.Settings.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(Ymm4Directory)\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <ProjectReference Include="..\..\src\EditAssist.Plugin\EditAssist.Plugin.csproj" />
    <ProjectReference Include="..\..\src\EditAssist.VersionManager\EditAssist.VersionManager.csproj" />
  </ItemGroup>
</Project>
