<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.3.0</Version>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildThisFileDirectory)=/src/</PathMap>
  </PropertyGroup>
</Project>
